import React, { useState } from 'react'
import MUIDialog from '@mui/material/Dialog';
import { Avatar, Button, DialogActions, DialogContent, DialogContentText, DialogTitle, Grid, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { useDispatch, useSelector } from 'react-redux';
import { setInstallmentDialog } from '../../store/slices/notificationSlice';
import BasicTable from '../table/BasicTable';
import { GRID_CHECKBOX_SELECTION_COL_DEF, isAutogeneratedRow, useGridApiRef } from '@mui/x-data-grid-premium';
import { parseLocalizedAmount } from 'utils/floatUtils';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import FormatListNumberedIcon from '@mui/icons-material/FormatListNumbered';
import PaidIcon from '@mui/icons-material/Paid';
import TabPanel from 'component/tab/TabPanel';
import InstallmentsInLease from 'features/leasing/components/InstallmentsInLease';
import ContractPaymentsInLease from 'features/leasing/components/ContractPaymentsInLease';
import TradeTransactionsInLease from 'features/leasing/components/TradeTransactionsInLease';
import DescriptionIcon from '@mui/icons-material/Description';

function InstallmentDialog(props) {
    const {lease_id} = props;

    const {dark} = useSelector((store) => store.auth);
    const {installmentDialog} = useSelector((store) => store.notification);
    const {installmentInformation,installmentsLoading,overdueInformation,overduesLoading} = useSelector((store) => store.installment);

    const dispatch = useDispatch();
    const apiRef = useGridApiRef();

    const [tabValue, setTabValue] = useState(0);

    const handleClose = () => {
        dispatch(setInstallmentDialog(false))
    };

    const handleChangeTabValue = (event, newTabValue) => {
        setTabValue(newTabValue);
    };

    const userColumns = [
        { field: 'sequency', headerName: 'Sıra No', flex: 1, type: 'number' },
        { field: 'payment_date', headerName: 'Ödeme Tarihi', flex: 1 },
        { field: 'payment', headerName: 'Ödeme', flex: 1, type: 'number',
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;

                return new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(params.value)
            },
        },
        { field: 'vat', headerName: 'KDV(%)', flex: 1, type: 'number',
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;

                return new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(params.value)
            },
        },
        { field: 'vat_amount', headerName: 'KDV Tutarı', flex: 1, type: 'number',
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;

                return new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(params.value)
            },
        },
        { field: 'amount', headerName: 'Toplam Ödeme', flex: 1, type: 'number',
            renderCell: (params) => {       
                const isAuto = isAutogeneratedRow(params.row);
                if (isAuto) {
                    const totalValue = amountTotal();
                    return (
                        <span style={{ color: dark ? '#42a5f5' : '#1565c0' }}>
                            {new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(totalValue)}
                        </span>
                    )
                } 

                return new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(params.value);
            }
        },
        { field: 'currency', headerName: 'Para Birimi', flex: 1 },
        { field: 'type_display', headerName: 'Ödeme Tipi', flex: 1 },
        //{...GRID_CHECKBOX_SELECTION_COL_DEF, width: 100,},
    ]

    const amountTotal = () => {
        if (apiRef.current) {
            const rows = Array.from(apiRef.current.getSortedRows().values());
            const total = rows.reduce((sum, row) => {
                // isAutogeneratedRow is used for aggregation footers, we should skip them.
                if (isAutogeneratedRow(row)) {
                    return sum;
                }
                const value = parseLocalizedAmount(row.amount);
                return sum + (Number.isFinite(value) ? value : 0);
            }, 0);

            return total;
        }
    };

    const rows = installmentInformation.map((row) => ({
        ...row,
        showCheckbox: row.overdue_amount > 0,
    }));


    return (
        <MUIDialog
        open={installmentDialog}
        onClose={handleClose}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
        elevation={3}
        variant="outlined"
        maxWidth="lg"
        fullWidth
        >
            <DialogTitle id="alert-dialog-title">
                <DescriptionIcon/> {`Kira Planı: ${rows ? rows.length > 0 ? rows[0]["lease"] : "" : ""} | Proje: ${rows ? rows.length > 0 ? rows[0]["project"] : "" : ""}`}
            </DialogTitle>
            <DialogContent>
                <DialogContentText id="alert-dialog-description">
                    <Stack spacing={2}>
                        {/* <Tabs
                        value={tabValue}
                        variant='scrollable'
                        scrollButtons="auto"
                        onChange={handleChangeTabValue}
                        >
                            <Tab label="Ödeme Tablosu" value={0} icon={<FormatListNumberedIcon/>} iconPosition="start"/>
                            <Tab label="TAHSİLATLAR" value={1} icon={<PaidIcon/>} iconPosition="start"/>
                            <Tab label="CARİ HESAP EKSTRESİ" value={2} icon={<ReceiptLongIcon/>} iconPosition="start"/>
                        </Tabs>
                        <TabPanel value={tabValue} index={0}>
                            <Grid container spacing={2}>
                                <Grid size={{xs:12,sm:12}}>
                                    <BasicTable
                                    title={`Kira Planı: ${rows ? rows.length > 0 ? rows[0]["lease"] : "" : ""} | Proje: ${rows ? rows.length > 0 ? rows[0]["project"] : "" : ""}`}
                                    rows={rows}
                                    columns={userColumns}
                                    getRowId={(row) => row.id}
                                    disableRowSelectionOnClick={true}
                                    loading={installmentsLoading}
                                    noToolbarButtons
                                    getRowClassName={(params) => params.row.type !== '1' ? `table-row-${dark ? "cream" : "celticglow"}` : ''}
                                    apiRef={apiRef}
                                    initialState={{
                                        aggregation: {
                                            model: {
                                                amount: 'sum',
                                            },
                                        },
                                    }}
                                    />
                                </Grid>
                            </Grid>
                        </TabPanel>
                        <TabPanel value={tabValue} index={1}>
                            <Grid container spacing={2}>
                                <Grid size={{xs:12,sm:12}}>
                                    dsfgdfgh
                                </Grid>
                            </Grid>
                        </TabPanel>
                        <TabPanel value={tabValue} index={2}>
                            <Grid container spacing={2}>
                                <Grid size={{xs:12,sm:12}}>
                                    sfg
                                </Grid>
                            </Grid>
                        </TabPanel> */}
                        <BasicTable
                        title=""
                        rows={rows}
                        columns={userColumns}
                        getRowId={(row) => row.id}
                        disableRowSelectionOnClick={true}
                        loading={installmentsLoading}
                        noToolbarButtons
                        getRowClassName={(params) => params.row.type !== '1' ? `table-row-${dark ? "cream" : "celticglow"}` : ''}
                        apiRef={apiRef}
                        initialState={{
                            aggregation: {
                                model: {
                                    amount: 'sum',
                                },
                            },
                        }}
                        />
                    </Stack>
                </DialogContentText>
            </DialogContent>
            <DialogActions className=''>
                <Button color="neutral" onClick={handleClose}>Cancel</Button>
            </DialogActions>
        </MUIDialog>
    )
}

export default InstallmentDialog
