services:
  web:
    container_name: arinet_frontend
    image: arinet_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./build:/usr/share/nginx/html
    command: ["npm", "start"]
    #command: ["npm", "run", "build"]
    restart: always
    networks:
      - arinet_network
networks:
  arinet_network:
    external: true