import { useGridApiRef } from '@mui/x-data-grid';
import React, { useEffect, useRef, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux';
import { fetchPartnerInformation } from 'store/slices/partners/partnerSlice';
import { setContractPaymentDialog, setInstallmentDialog, setPartnerDialog, setTradeTransactionDialog, setWarningNoticeDialog } from 'store/slices/notificationSlice';
import { fetchInstallmentInformation, setInstallmentsLoading } from 'store/slices/leasing/installmentSlice';
import { Box, Grid, IconButton } from '@mui/material';
import ListTable from 'component/table/ListTable';
import { setLeasesParams } from 'store/slices/leasing/leaseSlice';
import { fetchContractPaymentsInLease, fetchWarningNoticeInformation } from 'store/slices/contracts/contractSlice';
import PaidIcon from '@mui/icons-material/Paid';
import ContractPaymentDialog from 'component/dialog/ContractPaymentDialog';
import { cellProgress } from 'component/progress/CellProgress';
import FeedIcon from '@mui/icons-material/Feed';
import WarningNoticeDialog from 'component/dialog/WarningNoticeDialog';
import OverdueDetailDetailPanel from 'features/risk/components/OverdueDetailPanel';
import { fetchTradeTransactionsInLease } from 'store/slices/trade/tradeTransactionSlice';
import TradeTransactionDialog from 'component/dialog/TradeTransactionDialog';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import { isAutogeneratedRow } from '@mui/x-data-grid-premium';

function TrialBalanceContractDetailPanel(props) {
    const {uuid, trialBalanceContractTBs} = props;

    const {user} = useSelector((store) => store.auth);
    const {activeCompany} = useSelector((store) => store.organization);
    const {leases,leasesCount,leasesParams,leasesLoading} = useSelector((store) => store.lease);
    const {contractPaymentsParams} = useSelector((store) => store.contract);

    const dispatch = useDispatch();
    const apiRef = useGridApiRef();
    const detailApiRefs = useRef({});

    const [data, setData] = useState({})
    const [selectedRows, setSelectedRows] = useState([]);
    const isFirstSelection = useRef(true);

    useEffect(() => {
        let allSelectedRows = [];
        if (apiRef.current) {
            const tableRows = apiRef.current.getAllRowIds().map((id) => apiRef.current.getRow(id))
            const overdueRowIds = []
            tableRows.forEach((tableRow) => {
                if (tableRow.leaseflex_automation){
                    overdueRowIds.push(tableRow.id)
                }
            })
            
            if(overdueRowIds.length > 0){
                apiRef.current.selectRows(overdueRowIds,true,true);
                const map = apiRef.current.getSelectedRows();
                map.forEach((row) => allSelectedRows.push(row));
            }else {
                isFirstSelection.current = false;
            }
        }
    }, [])

    const columns = [
        { field: 'main_account_code', headerName: 'Ana Hesap Kodu', width: 100},
        { field: 'account_code', headerName: 'Hesap Kodu', width: 200 },
        { field: 'account_name', headerName: 'Hesap Adı', width: 400 },
        { field: 'contract', headerName: 'Sözleşme' },
        { field: 'currency', headerName: 'PB' },
        { field: 'balance_debit', headerName: 'Borç Toplamı', width: 140 , type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'balance_credit', headerName: 'Alacak Toplamı', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_debit', headerName: 'Borç Bakiyesi', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_credit', headerName: 'Alacak Bakiyesi', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_tl', headerName: 'TL Bakiye', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'balance_debit_alternate', headerName: 'Borç Toplam', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'balance_credit_alternate', headerName: 'Alacak Toplamı', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_debit_alternate', headerName: 'Borç Bakiyesi', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_credit_alternate', headerName: 'Alacak Bakiyesi', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'total_currency', headerName: 'Döviz Bakiye', width: 140, type: 'number', renderHeaderFilter: () => null, valueFormatter: (value) =>
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
    ]

    const handleProfileDialog = async (params,event) => {
        if(params.field==="partner"){
            await dispatch(fetchPartnerInformation(params.row.partner_crm_code)).unwrap();
            dispatch(setPartnerDialog(true));
        }else if(params.field==="code"){
            dispatch(setInstallmentsLoading(true));
            await dispatch(fetchInstallmentInformation({lease_code: params.row.code})).unwrap();
            dispatch(setInstallmentDialog(true));
            dispatch(setInstallmentsLoading(false));
        };
    };

    const handleWarningNoticeDialog = async (contract) => {
        dispatch(fetchWarningNoticeInformation({activeCompany,contract:contract}));
        dispatch(setWarningNoticeDialog(true));
    };

    return (
        <Box sx={{ pt: 2, pb: 2, pl: 8, pr: 8 }}>
            <ListTable
            title={trialBalanceContractTBs.length > 1 ? `${trialBalanceContractTBs[0].contract} - Mizan` : ""}
            height="auto"
            autoHeight
            //density="compact"
            rows={trialBalanceContractTBs}
            columns={columns}
            getRowId={(row) => row ? row.id : 0}
            loading={leasesLoading}
            setParams={(value) => dispatch(setLeasesParams(value))}
            onCellClick={handleProfileDialog}
            showCellVerticalBorder
            showColumnVerticalBorder
            outline
            noToolbarButtons
            getRowClassName={(params) => `super-app-theme--${params.row.overdue_amount > 0 ? "overdue" : ""}`}
            //noAllSelect
            //rowSelectionModel={selectedRows}
            //keepNonExistentRowsSelected
            //isRowSelected={(row) => row.overdue_amount > 0}
            //hideFooter
            noPagination
            apiRef={apiRef}
            initialState={{
                aggregation: {
                    model: {
                        overdue_amount: 'sum',
                    },
                },
            }}
            />
            <ContractPaymentDialog/>
            <WarningNoticeDialog/>
            <TradeTransactionDialog/>
        </Box>
    )
}

export default TrialBalanceContractDetailPanel
