import { useGridApiRef } from '@mui/x-data-grid';
import React, { useEffect, useRef, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux';
import { fetchPartnerInformation } from 'store/slices/partners/partnerSlice';
import { setAlert, setContractPaymentDialog, setDialog, setInstallmentDialog, setPartnerDialog, setTradeTransactionDialog, setComprehensiveWarningNoticeDialog } from 'store/slices/notificationSlice';
import { fetchInstallmentInformation, setInstallmentsLoading } from 'store/slices/leasing/installmentSlice';
import { Box, Button, Grid, IconButton, Stack } from '@mui/material';
import ListTable from 'component/table/ListTable';
import { setLeasesParams } from 'store/slices/leasing/leaseSlice';
import { fetchComprehensiveWarningNoticeInformation, fetchContractPaymentsInLease, fetchWarningNoticeInformation } from 'store/slices/contracts/contractSlice';
import PaidIcon from '@mui/icons-material/Paid';
import ContractPaymentDialog from 'component/dialog/ContractPaymentDialog';
import { cellProgress } from 'component/progress/CellProgress';
import FeedIcon from '@mui/icons-material/Feed';
import OverdueDetailDetailPanel from 'features/risk/components/OverdueDetailPanel';
import { fetchTradeTransactionsInLease } from 'store/slices/trade/tradeTransactionSlice';
import TradeTransactionDialog from 'component/dialog/TradeTransactionDialog';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import { isAutogeneratedRow } from '@mui/x-data-grid-premium';
import TableButton from 'component/button/TableButton';
import { fetchComprehensiveWarnedRiskPartners } from 'store/slices/leasing/riskPartnerSlice';
import axios from 'axios';
import DownloadIcon from '@mui/icons-material/Download';
import ComprehensiveWarningNoticeDialog from 'component/dialog/ComprehensiveWarningNoticeDialog ';
import { EmailIcon } from 'icons';
import Dialog from 'component/feedback/Dialog';


function ComprehensiveWarnedRiskPartnerDetailPanel(props) {
    const {uuid, riskPartnerLeases,project} = props;

    const {dark} = useSelector((store) => store.auth);
    const {activeCompany} = useSelector((store) => store.organization);
    const {leases,leasesCount,leasesParams,leasesLoading} = useSelector((store) => store.lease);
    const {contractPaymentsParams} = useSelector((store) => store.contract);
    const {warnedRiskPartnersParams,comprehensiveWarnedRiskPartnersParams} = useSelector((store) => store.riskPartner);

    const dispatch = useDispatch();
    const apiRef = useGridApiRef();
    const detailApiRefs = useRef({});

    const [data, setData] = useState({})
    const [selectedRows, setSelectedRows] = useState([]);
    const [fileUuid, setFileUuid] = useState({})
    const [fileContract, setFileContract] = useState({})
    const isFirstSelection = useRef(true);
    const [rowSelectionModel, setRowSelectionModel] = useState({
        type: 'include',
        ids: new Set(),
    });

    useEffect(() => {
        let allSelectedRows = [];
        if (apiRef.current) {
            const tableRows = apiRef.current.getAllRowIds().map((id) => apiRef.current.getRow(id))
            const overdueRowIds = []
            tableRows.forEach((tableRow) => {
                if (tableRow.leaseflex_automation){
                    overdueRowIds.push(tableRow.id)
                }
            })
            
            if(overdueRowIds.length > 0){
                apiRef.current.selectRows(overdueRowIds,true,true);
                const map = apiRef.current.getSelectedRows();
                map.forEach((row) => allSelectedRows.push(row));
            }else {
                isFirstSelection.current = false;
            }
        }
    }, [])

    const columns = [
        { field: 'code', headerName: 'Kira Planı', flex:2, renderCell: (params) => (
                <div style={{ cursor: 'pointer' }}>
                    {params.value}
                </div>
            )
        },
        { field: 'contract', headerName: 'Sözleşme', flex:2 },
        { field: 'block', headerName: 'Blok', flex:2 },
        { field: 'unit', headerName: 'Bağımsız Bölüm', flex:2 },
        { field: '', headerName: 'Tahsilatlar', flex:2,
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;
                return (
                    <Stack direction="row" spacing={1} sx={{alignItems: "center",height:'100%',}}>
                        <TableButton
                        icon={<PaidIcon/>}
                        onClick={()=>{dispatch(fetchContractPaymentsInLease({activeCompany,contract_uuid:params.row.contract_uuid}));dispatch(setContractPaymentDialog(true))}}
                        />
                    </Stack>
                )
            }
        },
        { field: '-trade_transactions', headerName: 'Cari Ekstre', flex:2,
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;
                return (
                    <Stack direction="row" spacing={1} sx={{alignItems: "center",height:'100%',}}>
                        <TableButton
                        icon={<ReceiptLongIcon/>}
                        onClick={()=>{dispatch(fetchTradeTransactionsInLease({activeCompany,lease_uuid:params.row.id}));dispatch(setTradeTransactionDialog(true))}}
                        />
                    </Stack>
                )
            }
        },
        { field: 'overdue_amount', headerName: 'Gecikme Tutarı', flex:2, type: 'number', renderHeaderFilter: () => null, cellClassName: (params) => {
                return params.value > 0 ? 'bg-red' : '';
            }
        },
        { field: 'currency', headerName: 'PB', flex:1 },
        { field: 'overdue_days', headerName: 'Gecikme Süresi', flex:2, type: 'number', renderHeaderFilter: () => null, renderCell: (params) => (
                params.row.overdue_amount > 0
                ?
                    params.value >= 0
                    ?
                        `${params.value} gün`
                    :
                        null
                :
                    null
                
            )
        },
        { field: 'paid_rate', headerName: 'Oran', flex:2, type: 'number', renderCell: cellProgress },
        { field: 'status', headerName: 'Durum', flex:2 },
        // { field: 'i', headerName: 'İhtar', flex: 2, renderCell: (params) => (
        //         params.row.status === "İhtar Çekildi"
        //         ?
        //             <Stack direction="row" spacing={1} sx={{alignItems: "center",height:'100%',}}>
        //                 <TableButton
        //                 text="İndir"
        //                 icon={<DownloadIcon/>}
        //                 onClick={() => getFile(params.row.id,params.row.contract)}
        //                 />
        //             </Stack>
        //         :
        //             null
        //     )
        // },
        { field: 'i', headerName: 'İhtar', flex: 2, renderCell: (params) => (
                        params.row.status === "İhtar Çekildi"
                        ?
                            <Stack direction="row" spacing={1} sx={{alignItems: "center",height:'100%',}}>
                                <TableButton
                                icon={<FeedIcon/>}
                                onClick={() => handleComprehensiveWarningNoticeDialog(params.row.id,params.row.contract)}
                                />
                            </Stack>
                        :
                            null
                    )
                },
        // { field: 'is_kdv_diff', headerName: 'KDV Durumu', flex:2, renderCell: (params) => (
        //         params.value
        //         ?
        //             "Kdv Farkı Var"
        //         :
        //             ""
                
        //     ),
        //     cellClassName: (params) => {
        //         return params.value ? 'bg-orange' : '';
        //     }
        // },
        { field: 'lease_status', headerName: 'Statü', flex:2 },
    ]

    const handleProfileDialog = async (params,event) => {
        if(params.field==="partner"){
            await dispatch(fetchPartnerInformation(params.row.partner_crm_code)).unwrap();
            dispatch(setPartnerDialog(true));
        }else if(params.field==="code"){
            dispatch(setInstallmentsLoading(true));
            await dispatch(fetchInstallmentInformation({lease_code: params.row.code})).unwrap();
            dispatch(setInstallmentDialog(true));
            dispatch(setInstallmentsLoading(false));
        };
    };

    const getFile = async (uuid,contract) => {
            dispatch(setDialog(false));
            try {
                const response = await axios.post('/risk/get_warning_notice/',
                    {
                        uuid: uuid,
                    },
                    {
                        responseType: "blob",
                        withCredentials: true
                    }
                );
                console.log(response.headers)
                const a = document.createElement("a");
                a.href = URL.createObjectURL(response.data);
                a.download = `${contract}.docx`;
                a.click();
                URL.revokeObjectURL(a.href);
            } catch (error) {
                dispatch(setAlert({status:'error',text:error.message}));
            } finally {
    
            }
        };

    const handleComprehensiveWarningNoticeDialog = async (uuid,contract) => {
        setFileUuid(uuid);
        setFileContract(contract);
        dispatch(fetchComprehensiveWarningNoticeInformation({activeCompany,contract:contract}));
        dispatch(setComprehensiveWarningNoticeDialog(true));
    };

    const sendEmail = async () => {
        dispatch(setDialog(false));
        try {
            const response = await axios.post('/communication/send_risk_email_selected/',
                {   
                    ac: activeCompany.id,
                    project: project,
                    risk_status:props.risk_status,
                    subject: "Ödeme Hatırlatma Bilgilendirmesi",
                    uuids: rowSelectionModel.type === 'exclude'
                        ? apiRef.current.getAllRowIds().filter(id => !rowSelectionModel.ids.has(id))
                        : Array.from(rowSelectionModel.ids),
                },
                {
                    withCredentials: true
                }
            );
            dispatch(fetchComprehensiveWarnedRiskPartners({activeCompany,params:{...comprehensiveWarnedRiskPartnersParams,project}}));
        } catch (error) {
            dispatch(setAlert({status:'error',text:error.message}));
        } finally {

        }
        
    };

    return (
        <Box sx={{ pt: 2, pb: 2, pl: 8, pr: 8 }}>
            <ListTable
            title={riskPartnerLeases.length > 1 ? `${riskPartnerLeases[0].partner} - ${riskPartnerLeases[0].partner_tc} Kira Planları` : ""}
            height="auto"
            autoHeight
            //density="compact"
            rows={riskPartnerLeases}
            columns={columns}
            getRowId={(row) => row ? row.id : 0}
            loading={leasesLoading}
            customFiltersLeft={
                <>
                    {
                        rowSelectionModel.ids.size > 0 || rowSelectionModel.type === 'exclude'
                        ?
                            <Button
                            variant='contained'
                            color='primary'
                            size='small'
                            onClick={() => {dispatch(setDialog(true));}}
                            sx={{mt:1,mb:1}}
                            endIcon={<EmailIcon/>}
                            >
                                Email Gönder
                            </Button>
                        :
                        null
                    } 
                </>
            }
            setParams={(value) => dispatch(setLeasesParams(value))}
            onCellClick={handleProfileDialog}
            showCellVerticalBorder
            showColumnVerticalBorder
            outline
            noToolbarButtons
            checkboxSelection
            onRowSelectionModelChange={(newRowSelectionModel) => {
                setRowSelectionModel(newRowSelectionModel);
            }}
            rowSelectionModel={rowSelectionModel}
            //getRowClassName={(params) => `super-app-theme--${params.row.overdue_amount > 0 ? "overdue" : ""}`}
            //noAllSelect
            //rowSelectionModel={selectedRows}
            //keepNonExistentRowsSelected
            //isRowSelected={(row) => row.overdue_amount > 0}
            //hideFooter
            noPagination
            apiRef={apiRef}
            initialState={{
                aggregation: {
                    model: {
                        overdue_amount: 'sum',
                    },
                },
            }}
            getDetailPanelHeight={() => "auto"}
            getDetailPanelContent={(params) => {return(<OverdueDetailDetailPanel leaseOverdues={params.row.overdues}></OverdueDetailDetailPanel>)}}
            />
            <ContractPaymentDialog/>
            <ComprehensiveWarningNoticeDialog
            fileUuid={fileUuid}
            fileContract={fileContract}
            edit={true}
            />
            <TradeTransactionDialog/>
            <Dialog
            title="Devam Etmek İstiyor musun?"
            text="Seçili kayıtları için ilgili müşterinin sistemde kayıtlı e-mail adresine e-mail gönderilecek."
            onClick={sendEmail}
            onClickColor='opposite'
            onClickText='Gönder'
            />
        </Box>
    )
}

export default ComprehensiveWarnedRiskPartnerDetailPanel
