import { Box, IconButton } from '@mui/material';
import { useGridApiRef } from '@mui/x-data-grid';
import React, { useEffect, useRef, useState } from 'react'
import ListTable from 'component/table/ListTable';
import { useDispatch, useSelector } from 'react-redux';
import { setLeasesParams } from 'store/slices/leasing/leaseSlice';
import { fetchPartnerInformation } from 'store/slices/partners/partnerSlice';
import { setAddBankActivityLeaseDialog, setAlert, setContractPaymentDialog, setInstallmentDialog, setPartnerDialog, setTradeTransactionDialog } from 'store/slices/notificationSlice';
import { fetchInstallmentInformation, setInstallmentsLoading } from 'store/slices/leasing/installmentSlice';
import { updateLeaseflexAutomationBankActivityLeases } from 'store/slices/leasing/collectionSlice';
import { setIsProgress } from 'store/slices/processSlice';
import axios from 'axios';
import CustomTableButton from 'component/table/CustomTableButton';
import AddBoxIcon from '@mui/icons-material/AddBox';
import { fetchBankActivities, fetchBankActivity, fetchBankActivityLeases, setBankActivitiesLoading } from 'store/slices/leasing/bankActivitySlice';
import ContractPaymentDialog from 'component/dialog/ContractPaymentDialog';
import { fetchContractPaymentsInLease } from 'store/slices/contracts/contractSlice';
import PaidIcon from '@mui/icons-material/Paid';
import OverdueDetailDetailPanel from 'features/risk/components/OverdueDetailPanel';
import { parseLocalizedAmount } from 'utils/floatUtils';
import AddBankActivityLeaseDialog from 'component/feedback/AddBankActivityLeaseDialog';
import { isAutogeneratedRow } from '@mui/x-data-grid-premium';
import { fetchTradeTransactionsInLease } from 'store/slices/trade/tradeTransactionSlice';
import TradeTransactionDialog from 'component/dialog/TradeTransactionDialog';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';

function DetailPanel(props) {
    const {uuid,bank_activity_leases,onOpen} = props;

    const {user, dark} = useSelector((store) => store.auth);
    const {activeCompany} = useSelector((store) => store.organization);
    const {bankActivitiesParams} = useSelector((store) => store.bankActivity);

    const dispatch = useDispatch();
    const apiRef = useGridApiRef();
    const detailApiRefs = useRef({});
    const isFirstSelection = useRef(true);

    const [data, setData] = useState({leases:{leases:[]}});
    const [selectedRows, setSelectedRows] = useState([]);
    

     const fetchData = async () => {
        const response = await dispatch(fetchBankActivity({activeCompany,params:{uuid}})).unwrap();
        console.log(response)
        setData(response);
        
        
    };

    useEffect(() => {
        fetchData();
        
        
    }, [activeCompany])


    useEffect(() => {
        let allSelectedRows = [];
        if (apiRef.current) {
            const tableRows = apiRef.current.getAllRowIds().map((id) => apiRef.current.getRow(id))
            const overdueRowIds = []
            tableRows.forEach((tableRow) => {
                if (tableRow.leaseflex_automation){
                    overdueRowIds.push(tableRow.id)
                }
            })
            
            if(overdueRowIds.length > 0){
                apiRef.current.selectRows(overdueRowIds,true,true);
                const map = apiRef.current.getSelectedRows();
                map.forEach((row) => allSelectedRows.push(row));
            }else {
                isFirstSelection.current = false;
            }
        }
        
    }, [data.leases])

    const columns = [
        { field: 'code', headerName: 'Kira Planı', flex:2, renderCell: (params) => (
                <div style={{ cursor: 'pointer' }}>
                    {params.value}
                </div>
            )
        },
        //{ field: 'contract', headerName: 'Sözleşme', flex:1.5 },
        { field: 'project', headerName: 'Proje', flex:2, renderCell: (params) => (
            params.value
            ?
                params.value.includes("KIZILBÜK")
                ?
                    "KIZILBÜK"
                :
                    params.value
            :
                ""
        )

        },
        { field: 'block', headerName: 'Blok', flex:2 },
        { field: 'unit', headerName: 'Bağımsız Bölüm', flex:1.5 },
        { field: 'devremulk', headerName: 'Dönem', flex:2 },
        { field: '', headerName: 'Tahsilatlar', flex:2,
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;

                return (
                    <IconButton aria-label='back' onClick={()=>{dispatch(fetchContractPaymentsInLease({activeCompany,contract:params.row.contract}));dispatch(setContractPaymentDialog(true))}}>
                        <PaidIcon/>
                    </IconButton>
                )
                
            },
            aggregable: false,
        },
        { field: '-trade_transactions', headerName: 'Cari Ekstre', flex:2,
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;
                return (
                    <IconButton aria-label='back' onClick={()=>{dispatch(fetchTradeTransactionsInLease({activeCompany,lease_id:params.row.lease_id}));dispatch(setTradeTransactionDialog(true))}}>
                        <ReceiptLongIcon/>
                    </IconButton>
                )
            }
        },
        { field: 'currency', headerName: 'PB', flex:1 },
        { field: 'last_payment', headerName: 'Devir Bedeli', flex:2, type: 'number', valueFormatter: (value) => 
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'overdue_days', headerName: 'Gecikme Günü', flex:2, type: 'number', renderHeaderFilter: () => null,
            renderCell: (params) => {
                const isAuto = isAutogeneratedRow(params.row)
                if (isAuto) return null;

                return (
                    `${params.value} gün`
                )
            },
            aggregable: false,
        },
        { field: 'overdue_amount', headerName: 'Gecikme Tutarı', flex:2, type: 'number',
            renderHeaderFilter: () => null,
            cellClassName: (params) => {
                return params.value > 0 ? 'bg-red' : '';
            }
        },
        { field: 'next_payment', headerName: 'Gelecek Ödeme', flex:2, type: 'number', valueFormatter: (value) => 
            new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(value)
        },
        { field: 'processed_amount', headerName: 'İşlenen Tutar', flex:2, editable: true,
            preProcessEditCellProps: (params: GridPreProcessEditCellProps) => {
                //const value = parseFloat(params.props.value);
                const convertedValue = parseLocalizedAmount(params.props.value)
                const isValid = Number.isFinite(convertedValue);
                return { ...params.props, value: isValid ? convertedValue : 0, error: 0 }
            
            },
            valueFormatter: (value) => {
                if (value === null || value === undefined) {
                    return ''; // boş göster
                }
                const convertedValue = parseLocalizedAmount(value);

                return  new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(convertedValue);
                //return Number(convertedValue);
            },
            renderCell: (params) => {       
                const isAuto = isAutogeneratedRow(params.row);
                if (isAuto) {
                    const totalValue = logProcessedAmountTotal();
                    return (
                        <span style={{ color: dark ? '#42a5f5' : '#1565c0' }}>
                            {new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(totalValue)}
                        </span>
                    )
                } 
                
                const convertedValue = parseLocalizedAmount(params.value);

                return (
                    <span style={convertedValue > 0 ? { color: dark ? '#3984f5ff' : '#0045B0' } : {}}>
                        {new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(convertedValue)}
                    </span>
                )
            }
        },
        { field: 'collection_status', headerName: 'Kalan Tutar', flex:2, 
            renderCell: (params) => {       
                const isAuto = isAutogeneratedRow(params.row);
                if (isAuto) {
                    const totalValue = logProcessedAmountTotal();
                    const remaining = data.amount - totalValue;
                    return (
                        <span style={{ color: dark ? '#42a5f5' : '#1565c0' }}>
                            {new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2,maximumFractionDigits: 2,}).format(remaining)}
                        </span>
                    )
                } 

                return null;
            }
         },
    ]

    const logProcessedAmountTotal = () => {
        if (apiRef.current) {
            const rows = Array.from(apiRef.current.getSortedRows().values());
            const total = rows.reduce((sum, row) => {
                // isAutogeneratedRow is used for aggregation footers, we should skip them.
                if (isAutogeneratedRow(row)) {
                    return sum;
                }
                const value = parseLocalizedAmount(row.processed_amount);
                return sum + (Number.isFinite(value) ? value : 0);
            }, 0);

            return total;
        }
    };

    const handleProfileDialog = async (params,event) => {
        if (event) {
            event.stopPropagation();
        }
        if(params.field==="partner"){
            await dispatch(fetchPartnerInformation(params.row.partner_crm_code)).unwrap();
            dispatch(setPartnerDialog(true));
        }else if(params.field==="code"){
            dispatch(setInstallmentsLoading(true));
            await dispatch(fetchInstallmentInformation({lease_code: params.row.code})).unwrap();
            dispatch(setInstallmentDialog(true));
            dispatch(setInstallmentsLoading(false));
        }
    };

    const previousSelectedRows = useRef(new Set());

    const handleSelectionChange = () => {
        const currentSelection = new Set(apiRef.current.getSelectedRows().keys());

        if (isFirstSelection.current) {
            isFirstSelection.current = false;
            previousSelectedRows.current = currentSelection;
            return;
        }

        const added = [...currentSelection].filter(id => !previousSelectedRows.current.has(id));
        const removed = [...previousSelectedRows.current].filter(id => !currentSelection.has(id));

        if (added.length > 0) {
            dispatch(updateLeaseflexAutomationBankActivityLeases({activeCompany,data:{uuids:added,select:true}})).unwrap().then(() => {
                dispatch(fetchBankActivities({activeCompany,params:{...bankActivitiesParams,paginate:false}}));
                dispatch(setBankActivitiesLoading(false));
            });
        }
        if (removed.length > 0) {
            dispatch(updateLeaseflexAutomationBankActivityLeases({activeCompany,data:{uuids:removed,select:false}})).unwrap().then(() => {
                dispatch(fetchBankActivities({activeCompany,params:{...bankActivitiesParams,paginate:false}}));
                dispatch(setBankActivitiesLoading(false));
            });
        }

        previousSelectedRows.current = currentSelection;
    };

    const handleProcessRowUpdate = async (newRow,oldRow) => {
        const convertedValue = parseLocalizedAmount(newRow.processed_amount)
        try {
            if (!Number.isFinite(convertedValue)) {
                throw new Error("Geçersiz sayı değeri");
            }

            try {
                const response = await axios.post(`/leasing/update_bank_activity_lease_processed_amount/`,
                    {
                        uuid: newRow.id,
                        amount: convertedValue
                    },
                    { 
                        withCredentials: true
                    },
                );
                dispatch(setAlert({status:response.data.status,text:response.data.message}))
            } catch (error) {
                if(error.response.data){
                    dispatch(setAlert({status:error.response.data.status,text:error.response.data.message}));
                }else{
                    dispatch(setAlert({status:"error",text:"Sorry, something went wrong!"}));
                };
                return null
            }  finally {
                dispatch(fetchBankActivities({activeCompany,params:{...bankActivitiesParams,paginate:false}}));
            }


            const updatedRow = { ...newRow, isUpdated: true };

            return updatedRow;
        } catch (error) {
            return {
                ...oldRow,
                processed_amount: oldRow.processed_amount
            };
        } 
    };


    return (
        <Box sx={{ pt: 2, pb: 2, pl: 8, pr: 8 }}>
            <ListTable
            title={data.leases.leases.length > 0 ? `${data.leases.leases[0].partner} - ${data.leases.leases[0].partner_tc} Kira Planları` : ""}
            height="auto"
            autoHeight
            rows={data.leases.leases}
            columns={columns}
            getRowId={(row) => row ? row.id : 0}
            specialButtons={
                    <>
                        <CustomTableButton
                        title="Yeni"
                        onClick={() => {dispatch(setAddBankActivityLeaseDialog(true));}}
                        icon={<AddBoxIcon fontSize="small"/>}
                        disabled={!data.is_third_person || (data.is_third_person && data.third_person_status === "cleared") ? false : true}
                        />
                    </>
                }
            setParams={(value) => dispatch(setLeasesParams(value))}
            onCellClick={handleProfileDialog}
            showCellVerticalBorder
            showColumnVerticalBorder
            outline
            noToolbarButtons
            getRowClassName={(params) => `super-app-theme--${params.row.overdue_amount > 0 ? "overdue" : ""}`}
            //noAllSelect
            checkboxSelection={true}
            disableRowSelectionOnClick={true}
            onRowSelectionModelChange={handleSelectionChange}
            //rowSelectionModel={selectedRows}
            keepNonExistentRowsSelected
            //isRowSelected={(row) => row.overdue_amount > 0}
            //hideFooter
            noPagination
            apiRef={apiRef}
            initialState={{
                aggregation: {
                    model: {
                        overdue_amount: 'sum',
                        next_payment: 'sum',
                        last_payment: 'sum',
                    },
                },
            }}
            processRowUpdate={handleProcessRowUpdate}
            onProcessRowUpdateError={(error) => console.log(error)}
            //cellFontSize="12px"
            getDetailPanelHeight={() => "auto"}
            getDetailPanelContent={(params) => {return(<OverdueDetailDetailPanel leaseOverdues={params.row.overdues}></OverdueDetailDetailPanel>)}}
            />
            <AddBankActivityLeaseDialog
            handleClose={() => dispatch(setAddBankActivityLeaseDialog(false))}
            submitURL="/leasing/add_bank_activity_lease"
            startEvent={() => dispatch(setBankActivitiesLoading(true))}
            finalEvent={() => {/*dispatch(fetchBankActivities({activeCompany}));*/dispatch(setBankActivitiesLoading(false));}}
            uuid={uuid}
            />
            <ContractPaymentDialog/>
            <TradeTransactionDialog/>
        </Box>
    )
}

export default DetailPanel
